servers:
  web:
    hosts:
      - once-fizzy-101
  jobs:
    hosts:
      - once-fizzy-101

proxy:
  hosts:
    - 37s.fizzy.37signals.com
    - dev.fizzy.37signals.com
    - qa.fizzy.37signals.com

ssh:
  user: app
